### PR TITLE
Fix for Issue #2: Add code to eat the UnsupportedVersionException for brokers that don'…

### LINKED ISSUE #2: Discovery fails with Kafka DESCRIBE_ACLS
When trying to connect to a 2.8.1 Kafka Instance I'm getting the following error:

```
com.event.discovery.agent.framework.exception.EventDiscoveryAgentException: Error getting kafka consumers
	at com.event.discovery.agent.kafkaCommon.plugin.AbstractApacheKafkaPlugin.getBrokerConfig(AbstractApacheKafkaPlugin.java:61)
	at com.event.discovery.agent.apps.eventDiscovery.EventDiscoveryApp.start(EventDiscoveryApp.java:125)
	at com.event.discovery.agent.apps.eventDiscovery.RealtimeEventDiscoveryApp.lambda$start$0(RealtimeEventDiscoveryApp.java:59)
	at com.event.discovery.agent.framework.task.RunnableJob.run(RunnableJob.java:39)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_ACLS
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.event.discovery.agent.kafkaCommon.KafkaCommon.discoveryKafkaAcls(KafkaCommon.java:397)
	at com.event.discovery.agent.kafkaCommon.KafkaCommon.buildKafkaDiscoveryData(KafkaCommon.java:202)
	at com.event.discovery.agent.kafkaCommon.plugin.AbstractApacheKafkaPlugin.getBrokerConfig(AbstractApacheKafkaPlugin.java:58)
	... 6 common frames omitted
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_ACLS

Exception in thread "EDA-1" com.event.discovery.agent.framework.exception.EventDiscoveryAgentException: Error getting kafka consumers
	at com.event.discovery.agent.framework.task.RunnableJob.handleException(RunnableJob.java:53)
	at com.event.discovery.agent.framework.task.RunnableJob.run(RunnableJob.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834
```

### PR DESCRIPTION
**Pull request by gregmeldrum**
Fix for Issue #2: Add code to eat the UnsupportedVersionException for brokers that don't support ACL queries.

The discovery tool was already eating other exception types so just added the UnsupportedVersionException to the list since we want to scan to succeed even if the particular broker does not support the ACL query.

### CODE REVIEW

File: service/services/eventDiscoveryService/install/offline/awsmsk/build.sh [hunk 1]
```diff
@@ -1,3 +1,3 @@
-cp ../../../target/event-discovery-agent-1.0-SNAPSHOT.jar .
-docker build --build-arg JAR_FILE=event-discovery-agent-1.0-SNAPSHOT.jar --tag event-discovery-agent:1.0 .
-rm ./event-discovery-agent-1.0-SNAPSHOT.jar
+cp ../../../target/event-discovery-agent-app-1.0-SNAPSHOT.jar .
```
Comment (gregmeldrum) [inline service/services/eventDiscoveryService/install/offline/awsmsk/build.sh:1]: This is unrelated to the reported error, but it will allow the easy creation of a docker container from the built jar.

File: service/services/eventDiscoveryService/src/test/java/com/event/discovery/agent/integrationTests/offline/kafkaCommon/kafka/KafkaEventDiscoveryTestsIT.java [hunk 2]
```diff
@@ -371,6 +372,27 @@ public void testAclError() throws Exception {
         assertThat(status.getStatus(), is(JobStatus.ERROR));
     }
 
+    @Test
```
Comment (gregmeldrum) [inline service/services/eventDiscoveryService/src/test/java/com/event/discovery/agent/integrationTests/offline/kafkaCommon/kafka/KafkaEventDiscoveryTestsIT.java:375]: Following TDD principals, this is the test that was first added, which failed, but then passed once the fix was added to the application.
